#!/usr/bin/python
import subprocess as sp
import os

muted = sp.Popen("amixer sget 'Master'", shell=True, stdout=sp.PIPE).stdout.read().decode('utf-8').split(' ')[26][1:-2]

os.system(f"amixer sset 'Master' {'on' if muted == 'off' else 'off'} &> /dev/null")
os.system("refbar")
