#!/usr/bin/python
import subprocess as sp
import os

vollevel = int(sp.Popen("amixer sget 'Master'", shell=True, stdout=sp.PIPE).stdout.read().decode('utf-8').split(' ')[24].lstrip('[').rstrip('%]'))

vollevel = 100 if vollevel > 95 else vollevel + 5

os.system(f"amixer sset 'Master' {vollevel}% on &> /dev/null")
os.system("refbar")
